export const dummyPlayersList = [
  {
    id: "324358",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 820278000,
    countryId: "189",
    clubId: "405",
    playerInfo: {
      id: "324358",
      name: "Ollie Watkins",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/324358-1708341279.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/324358-1708341279.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "363205",
    marketValue: { value: 65000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 860018400,
    countryId: "26",
    clubId: "11",
    playerInfo: {
      id: "363205",
      name: "Gabriel Jesus",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/363205-1669711141.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/363205-1669711141.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "318528",
    marketValue: { value: 65000000, currency: "€", progression: 1 },
    marketValueDate: 1717538400,
    birthday: 870818400,
    countryId: "50",
    clubId: "46",
    playerInfo: {
      id: "318528",
      name: "Marcus Thuram",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/318528-1662966601.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/318528-1662966601.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "444523",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 872632800,
    countryId: "26",
    clubId: "379",
    playerInfo: {
      id: "444523",
      name: "Lucas Paquetá",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/444523-1695370009.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/444523-1695370009.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "344381",
    marketValue: { value: 65000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 879462000,
    countryId: "50",
    clubId: "631",
    playerInfo: {
      id: "344381",
      name: "C. Nkunku",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/344381-1663686834.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/344381-1663686834.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "325443",
    marketValue: { value: 65000000, currency: "€", progression: 1 },
    marketValueDate: 1717624800,
    birthday: 896911200,
    countryId: "147",
    clubId: "336",
    playerInfo: {
      id: "325443",
      name: "V. Gyökeres",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/325443-1693591840.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/325443-1693591840.jpg?lm=1",
      imageSource: "Sporting CP",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "326031",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716933600,
    birthday: 934408800,
    countryId: "122",
    clubId: "27",
    playerInfo: {
      id: "326031",
      name: "M. de Ligt",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/326031-1700659567.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/326031-1700659567.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "357498",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 949014000,
    countryId: "215",
    clubId: "506",
    playerInfo: {
      id: "357498",
      name: "D. Vlahović",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/357498-1683293071.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/357498-1683293071.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "486049",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 1022450400,
    countryId: "19",
    clubId: "281",
    playerInfo: {
      id: "486049",
      name: "Jérémy Doku",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/486049-1666699113.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/486049-1666699113.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "610442",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 1044313200,
    countryId: "39",
    clubId: "985",
    playerInfo: {
      id: "610442",
      name: "Rasmus Højlund",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/610442-1699471458.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/610442-1699471458.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "203460",
    marketValue: { value: 60000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 810684000,
    countryId: "189",
    clubId: "281",
    playerInfo: {
      id: "203460",
      name: "Jack Grealish",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/203460-1676499047.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/203460-1676499047.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "516716",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 858639600,
    countryId: "26",
    clubId: "506",
    playerInfo: {
      id: "516716",
      name: "Bremer",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/516716-1661269026.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/516716-1661269026.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "288230",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717365600,
    birthday: 863647200,
    countryId: "50",
    clubId: "583",
    playerInfo: {
      id: "288230",
      name: "O. Dembélé",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/288230-1684148641.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/288230-1684148641.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "339808",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 876088800,
    countryId: "50",
    clubId: "5",
    playerInfo: {
      id: "339808",
      name: "Theo Hernández",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/339808-1663574533.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/339808-1663574533.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Lateral izquierdo",
          shortName: "LI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "258923",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 878252400,
    countryId: "189",
    clubId: "985",
    playerInfo: {
      id: "258923",
      name: "Marcus Rashford",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/258923-1674473054.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/258923-1674473054.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "401530",
    marketValue: { value: 60000000, currency: "€", progression: -1 },
    marketValueDate: 1717711200,
    birthday: 885078000,
    countryId: "26",
    clubId: "418",
    playerInfo: {
      id: "401530",
      name: "Éder Militão",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/401530-1689002515.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/401530-1689002515.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "355915",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 893628000,
    countryId: "9",
    clubId: "148",
    playerInfo: {
      id: "355915",
      name: "Cristian Romero",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/355915-1665609429.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/355915-1665609429.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "398073",
    marketValue: { value: 60000000, currency: "€", progression: -1 },
    marketValueDate: 1717365600,
    birthday: 910134000,
    countryId: "107",
    clubId: "583",
    playerInfo: {
      id: "398073",
      name: "Achraf Hakimi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/398073-1672304327.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/398073-1672304327.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Lateral derecho",
          shortName: "LD",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "368887",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1716933600,
    birthday: 950655600,
    countryId: "19",
    clubId: "23826",
    playerInfo: {
      id: "368887",
      name: "Loïs Openda",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/368887-1713944805.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/368887-1713944805.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "503733",
    marketValue: { value: 60000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 982969200,
    countryId: "189",
    clubId: "762",
    playerInfo: {
      id: "503733",
      name: "Anthony Gordon",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/503733-1660588736.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/503733-1660588736.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "709187",
    marketValue: { value: 60000000, currency: "€", progression: 1 },
    marketValueDate: 1717711200,
    birthday: 1026424800,
    countryId: "157",
    clubId: "621",
    playerInfo: {
      id: "709187",
      name: "Nico Williams",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/709187-1709676169.png?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/709187-1709676169.png?lm=1",
      imageSource: "Athletic Club",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "810092",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717365600,
    birthday: 1141772400,
    countryId: "50",
    clubId: "583",
    playerInfo: {
      id: "810092",
      name: "W. Zaïre-Emery",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/810092-1672303575.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/810092-1672303575.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "7", name: "Mediocentro", shortName: "MC", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "148455",
    marketValue: { value: 55000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 708559200,
    countryId: "2",
    clubId: "31",
    playerInfo: {
      id: "148455",
      name: "Mohamed Salah",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/148455-1700651360.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/148455-1700651360.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "257455",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 805240800,
    countryId: "136",
    clubId: "931",
    playerInfo: {
      id: "257455",
      name: "João Palhinha",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/257455-1684773447.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/257455-1684773447.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "6", name: "Pivote", shortName: "PIV", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "335721",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 876261600,
    countryId: "189",
    clubId: "11",
    playerInfo: {
      id: "335721",
      name: "Ben White",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/335721-1683275943.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/335721-1683275943.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Lateral derecho",
          shortName: "LD",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "479999",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 899071200,
    countryId: "189",
    clubId: "873",
    playerInfo: {
      id: "479999",
      name: "Eberechi Eze",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/479999-1678466922.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/479999-1678466922.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "395516",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 931298400,
    countryId: "50",
    clubId: "405",
    playerInfo: {
      id: "395516",
      name: "Moussa Diaby",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/395516-1642608355.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/395516-1642608355.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "487465",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 952556400,
    countryId: "136",
    clubId: "543",
    playerInfo: {
      id: "487465",
      name: "Pedro Neto",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/487465-1709158892.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/487465-1709158892.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "431755",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 956613600,
    countryId: "147",
    clubId: "148",
    playerInfo: {
      id: "431755",
      name: "D. Kulusevski",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/431755-1684943454.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/431755-1684943454.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "557459",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 987631200,
    countryId: "122",
    clubId: "148",
    playerInfo: {
      id: "557459",
      name: "M. van de Ven",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/557459-1657202743.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/557459-1657202743.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "566723",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 1008111600,
    countryId: "50",
    clubId: "873",
    playerInfo: {
      id: "566723",
      name: "Michael Olise",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/566723-1696598775.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/566723-1696598775.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "616341",
    marketValue: { value: 55000000, currency: "€", progression: -1 },
    marketValueDate: 1717365600,
    birthday: 1024437600,
    countryId: "136",
    clubId: "583",
    playerInfo: {
      id: "616341",
      name: "Nuno Mendes",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/616341-1672304855.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/616341-1672304855.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Lateral izquierdo",
          shortName: "LI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "670681",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1717624800,
    birthday: 1096236000,
    countryId: "136",
    clubId: "294",
    playerInfo: {
      id: "670681",
      name: "João Neves",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/670681-1701295511.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/670681-1701295511.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "6", name: "Pivote", shortName: "PIV", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "971570",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1711580400,
    birthday: 1153432800,
    countryId: "26",
    clubId: "1023",
    playerInfo: {
      id: "971570",
      name: "Endrick",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/971570-1682691107.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/971570-1682691107.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "88755",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 678060000,
    countryId: "19",
    clubId: "281",
    playerInfo: {
      id: "88755",
      name: "Kevin De Bruyne",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/88755-1713391485.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/88755-1713391485.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "181767",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1717365600,
    birthday: 768866400,
    countryId: "26",
    clubId: "583",
    playerInfo: {
      id: "181767",
      name: "Marquinhos",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/181767-1672303747.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/181767-1672303747.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "161056",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1716933600,
    birthday: 792198000,
    countryId: "40",
    clubId: "27",
    playerInfo: {
      id: "161056",
      name: "Joshua Kimmich",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/161056-1700039639.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/161056-1700039639.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Lateral derecho",
          shortName: "LD",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "251664",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 826930800,
    countryId: "189",
    clubId: "1148",
    playerInfo: {
      id: "251664",
      name: "Ivan Toney",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/251664-1677676808.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/251664-1677676808.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "353366",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 827967600,
    countryId: "50",
    clubId: "46",
    playerInfo: {
      id: "353366",
      name: "Benjamin Pavard",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/353366-1713819215.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/353366-1713819215.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "243714",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1716933600,
    birthday: 834616800,
    countryId: "50",
    clubId: "27",
    playerInfo: {
      id: "243714",
      name: "Kingsley Coman",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/243714-1700040256.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/243714-1700040256.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "338424",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717711200,
    birthday: 835394400,
    countryId: "157",
    clubId: "681",
    playerInfo: {
      id: "338424",
      name: "Mikel Merino",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/338424-1716803831.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/338424-1716803831.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "7", name: "Mediocentro", shortName: "MC", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "340950",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 849654000,
    countryId: "136",
    clubId: "31",
    playerInfo: {
      id: "340950",
      name: "Diogo Jota",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/340950-1716296423.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/340950-1716296423.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "411295",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717711200,
    birthday: 850518000,
    countryId: "26",
    clubId: "131",
    playerInfo: {
      id: "411295",
      name: "Raphinha",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/411295-1665127690.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/411295-1665127690.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "314875",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 851036400,
    countryId: "189",
    clubId: "379",
    playerInfo: {
      id: "314875",
      name: "Jarrod Bowen",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/314875-1662362005.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/314875-1662362005.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "198116",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 879116400,
    countryId: "75",
    clubId: "46",
    playerInfo: {
      id: "198116",
      name: "F. Dimarco",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/198116-1661511006.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/198116-1661511006.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Lateral izquierdo",
          shortName: "LI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "360518",
    marketValue: { value: 50000000, currency: "€", progression: 1 },
    marketValueDate: 1717538400,
    birthday: 888620400,
    countryId: "122",
    clubId: "800",
    playerInfo: {
      id: "360518",
      name: "T. Koopmeiners",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/360518-1707302998.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/360518-1707302998.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "293385",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716933600,
    birthday: 894492000,
    countryId: "157",
    clubId: "23826",
    playerInfo: {
      id: "293385",
      name: "Dani Olmo",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/293385-1711546268.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/293385-1711546268.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "601883",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 904168800,
    countryId: "136",
    clubId: "281",
    playerInfo: {
      id: "601883",
      name: "Matheus Nunes",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/601883-1693561106.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/601883-1693561106.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "7", name: "Mediocentro", shortName: "MC", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "423440",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717711200,
    birthday: 917910000,
    countryId: "157",
    clubId: "681",
    playerInfo: {
      id: "423440",
      name: "M. Zubimendi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/423440-1684149419.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/423440-1684149419.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "6", name: "Pivote", shortName: "PIV", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "434675",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 926028000,
    countryId: "122",
    clubId: "31",
    playerInfo: {
      id: "434675",
      name: "Cody Gakpo",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/434675-1682690965.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/434675-1682690965.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
];

export const playerDetailsDummyResponse = {
  data: {
    share: {
      title: "Lionel Messi - Perfil del jugador",
      url: "https://www.transfermarkt.es/lionel-messi/profil/spieler/28003",
      description: "Este es el perfil de jugador de Lionel Messi.",
    },
    playerProfile: {
      playerID: "28003",
      playerImage:
        "https://img.a.transfermarkt.technology/portrait/medium/28003-1710080339.jpg?lm=1",
      playerName: "Lionel Messi",
      playerFullName: "Lionel Messi",
      birthplace: "Rosario",
      dateOfBirth: "24/06/1987",
      dateOfDeath: null,
      playerShirtNumber: "10",
      birthplaceCountry: "Argentina",
      birthplaceCountryImage:
        "https://tmssl.akamaized.net/images/flagge/verysmall/9.png?lm=1520611569",
      age: "36",
      height: "1,70",
      foot: "izquierdo",
      internationalTeam: "Argentina",
      internationalTeamImage:
        "https://tmssl.akamaized.net/images/flagge/verysmall/9.png?lm=1520611569",
      internationalTeamStatus: "Selección",
      internationalGames: "180",
      internationalGoals: "106",
      internationalTeamShortTag: "A",
      internationalShirtNumber: "10",
      internationalWmMember: true,
      internationalValueRank: 149,
      country: "Argentina",
      countrynameEN: "Argentina",
      countryImage:
        "https://tmssl.akamaized.net/images/flagge/verysmall/9.png?lm=1520611569",
      countryShortName: "ARG",
      secondCountry: "España",
      secondCountryImage:
        "https://tmssl.akamaized.net/images/flagge/verysmall/157.png?lm=1520611569",
      league: "Major League Soccer",
      leaguenameEN: "Major League Soccer",
      leagueLogo:
        "https://tmssl.akamaized.net/images/logo/normal/mls1.png?lm=1612117632",
      clubImage:
        "https://tmssl.akamaized.net/images/wappen/medium/69261.png?lm=1573561237",
      club: "Inter Miami CF",
      clubnameEN: "Inter Miami CF",
      clubID: "69261",
      loan: {
        loan: "",
        loanStart: "",
        loanUntil: "",
        contractOptions: "",
        ownerName: "",
        ownerID: "",
        ownerImage: "",
        ownerContractUntil: "",
      },
      contractExpiryDate: "31/12/2025",
      agent: "Miembro de su familia",
      agentId: "1207",
      agentVerificationStatus: null,
      agentVerificationDate: false,
      outfitter: "",
      positionGroup: "Sturm",
      playerMainPosition: "Extremo derecho",
      playerSecondPosition: "Delantero centro",
      playerThirdPosition: "Mediapunta",
      marketValue: "30,00",
      marketValueCurrency: "€",
      marketValueNumeral: "mill.",
      marketValueLastChange: "25/03/2024",
      relatedness: [
        {
          id: "55306",
          personName: "Maxi Biancucchi",
          personGroup: "spieler",
          personID: "59303",
          degreeOfRelationship: "primo",
        },
        {
          id: "82727",
          personName: "E. Biancucchi",
          personGroup: "spieler",
          personID: "90036",
          degreeOfRelationship: "primo",
        },
      ],
      injury: {
        id: "",
        title: "",
        until: "-",
        rehabilitationFlag: "",
      },
      absence: {
        id: "",
        title: "",
        until: "-",
        competitionID: "",
        matches: "",
      },
      allSuspensions: [],
    },
    performanceSeasons: [
      {
        key: "2023",
        title: "23/24",
      },
      {
        key: "2022",
        title: "22/23",
      },
      {
        key: "2021",
        title: "21/22",
      },
      {
        key: "2020",
        title: "20/21",
      },
      {
        key: "2019",
        title: "19/20",
      },
      {
        key: "2018",
        title: "18/19",
      },
      {
        key: "2017",
        title: "17/18",
      },
      {
        key: "2016",
        title: "16/17",
      },
      {
        key: "2015",
        title: "15/16",
      },
      {
        key: "2014",
        title: "14/15",
      },
      {
        key: "2013",
        title: "13/14",
      },
      {
        key: "2012",
        title: "12/13",
      },
      {
        key: "2011",
        title: "11/12",
      },
      {
        key: "2010",
        title: "10/11",
      },
      {
        key: "2009",
        title: "09/10",
      },
      {
        key: "2008",
        title: "08/09",
      },
      {
        key: "2007",
        title: "07/08",
      },
      {
        key: "2006",
        title: "06/07",
      },
      {
        key: "2005",
        title: "05/06",
      },
      {
        key: "2004",
        title: "04/05",
      },
      {
        key: "2003",
        title: "03/04",
      },
    ],
    heroImages: [
      {
        id: "132837",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1711467863-132837.jpg?lm=1711467875",
        source: "IMAGO",
      },
      {
        id: "120754",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-argentinien-2022-1698689902-120754.jpg?lm=1698689910",
        source: "IMAGO",
      },
      {
        id: "116540",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-inter-miami-1694590069-116540.jpg?lm=1694590099",
        source: "imago images",
      },
      {
        id: "116229",
        url: "https://tmssl.akamaized.net/images/foto/normal/messi-lionel-2023-argentina-1694190597-116229.jpg?lm=1694190619",
        source: "fotobaires.com",
      },
      {
        id: "114379",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1692504890-114379.jpg?lm=1692504905",
        source: "IMAGO",
      },
      {
        id: "112152",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-inter-miami-cf-1690045378-112152.jpg?lm=1690045398",
        source: "IMAGO",
      },
      {
        id: "112129",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-miami-1689969052-112129.jpeg?lm=1689969177",
        source: "IMAGO",
      },
      {
        id: "108539",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-paris-saint-germain-2023-1685872213-108539.jpg?lm=1685872230",
        source: "IMAGO",
      },
      {
        id: "98673",
        url: "https://tmssl.akamaized.net/images/foto/normal/argentina-campeon-del-mundo-1671389672-98673.jpeg?lm=1671389733",
        source: "IMAGO",
      },
      {
        id: "98686",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-argentinien-wm-2022-1671430743-98686.jpg?lm=1671430759",
        source: "IMAGO",
      },
      {
        id: "98308",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-trifft-fur-argentinien-gegen-die-niederlande-wm-2022-1670619640-98308.jpg?lm=1670619666",
        source: "IMAGO",
      },
      {
        id: "97535",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-argentina-world-cup-2022-1669496833-97535.jpg?lm=1669496856",
        source: "IMAGO",
      },
      {
        id: "97148",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-argentina-wc-2022-1019555176h-1669130412-97148.jpg?lm=1669130439",
        source: "IMAGO",
      },
      {
        id: "93360",
        url: "https://tmssl.akamaized.net/images/foto/normal/messi-lionel-2022-23-seleccion-argentina-1664377743-93360.jpg?lm=1664377754",
        source: "IMAGO",
      },
      {
        id: "89763",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-psg-2022-23-1659958415-89763.jpg?lm=1659958429",
        source: "IMAGO",
      },
      {
        id: "69935",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-psg-2021-1630297043-69935.jpg?lm=1630297056",
        source: "IMAGO",
      },
      {
        id: "68922",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-paris-saint-germain-2021-1628864113-68922.jpg?lm=1628864133",
        source: "IMAGO",
      },
      {
        id: "68725",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-paris-st-germain-2021-1628677399-68725.jpg?lm=1628677410",
        source: "IMAGO",
      },
      {
        id: "9885",
        url: "https://tmssl.akamaized.net/images/foto/normal/messi-1493045428-9885.jpg?lm=1493045461",
        source: "IMAGO",
      },
      {
        id: "58808",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-fc-barcelona-2020-2021-1615872755-58808.jpg?lm=1615872773",
        source: "IMAGO",
      },
      {
        id: "39854",
        url: "https://tmssl.akamaized.net/images/foto/normal/messi-barcelona-1590668606-39854.jpg?lm=1590668596",
        source: "TM/IMAGO",
      },
      {
        id: "20148",
        url: "https://tmssl.akamaized.net/images/foto/normal/suarez-messi-dembele-1548687465-20148.jpg?lm=1548687490",
        source: "IMAGO",
      },
      {
        id: "41968",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-ballon-dor-2019-1592819026-41968.jpg?lm=1592819001",
        source: "IMAGO",
      },
      {
        id: "20204",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-fc-barcelona-1548770350-20204.jpg?lm=1548770369",
        source: "IMAGO",
      },
      {
        id: "26423",
        url: "https://tmssl.akamaized.net/images/foto/normal/messi-1570628108-26423.jpg?lm=1570628121",
        source: "IMAGO",
      },
      {
        id: "25426",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-fc-barcelona-1567748810-25426.jpg?lm=1567748836",
        source: "IMAGO",
      },
      {
        id: "25004",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-transfermarkt-spieler-der-laliga-saison-2018-19-1566816872-25004.jpg?lm=1566816882",
        source: "TM/LionelMessi",
      },
      {
        id: "54096",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-fc-barcelona-1610004379-54096.jpg?lm=1610004386",
        source: "IMAGO",
      },
      {
        id: "53594",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-fc-barcelona-2020-2021-1608727492-53594.jpg?lm=1608727512",
        source: "IMAGO",
      },
      {
        id: "20199",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-luis-suarez-1548769695-20199.jpg?lm=1548769717",
        source: "IMAGO",
      },
      {
        id: "20203",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1548770181-20203.jpg?lm=1548770203",
        source: "IMAGO",
      },
      {
        id: "12154",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1506921740-12154.jpg?lm=1506921752",
        source: "IMAGO",
      },
      {
        id: "12248",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1507649274-12248.jpg?lm=1507649293",
        source: "IMAGO",
      },
      {
        id: "6504",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1478622373-6504.jpg?lm=1483606205",
        source: "IMAGO",
      },
      {
        id: "5804",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1471008317-5804.jpg?lm=1483606110",
        source: "IMAGO",
      },
      {
        id: "5622",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1467208453-5622.jpg?lm=1483606087",
        source: "IMAGO",
      },
      {
        id: "4925",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1454508603-4925.jpg?lm=1483606013",
        source: "IMAGO",
      },
      {
        id: "4609",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1421073766-4609.jpg?lm=1483605977",
        source: "IMAGO",
      },
      {
        id: "224",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1401789362-224.jpg?lm=1483605491",
        source: "Getty Images",
      },
      {
        id: "219",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1401786445-219.jpg?lm=1483605491",
        source: "Getty Images",
      },
      {
        id: "218",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1401786427-218.jpg?lm=1483605491",
        source: "Getty Images",
      },
      {
        id: "37588",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-2007-1588590273-37588.jpg?lm=1588590278",
        source: "IMAGO",
      },
      {
        id: "6134",
        url: "https://tmssl.akamaized.net/images/foto/normal/lionel-messi-1473415845-6134.jpg?lm=1483606150",
        source: "IMAGO",
      },
    ],
  },
};

export const dummySearchRes = {
  data: {
    count: {
      players: 543,
      coaches: 39,
      clubs: 58,
      competitions: 1,
      referees: 35,
    },
    players: [
      {
        id: "28003",
        playerName: "Lionel Messi",
        firstName: "Lionel",
        lastName: "Messi",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/9.png?lm=1520611569",
        club: "Inter Miami CF",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/28003-1710080339.jpg?lm=1",
      },
      {
        id: "449151",
        playerName: "Junior Messias",
        firstName: "Junior",
        lastName: "Messias",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/26.png?lm=1520611569",
        club: "Genua CFC",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/449151-1663575000.jpg?lm=1",
      },
      {
        id: "744024",
        playerName: "João Marcelo",
        firstName: "João",
        lastName: "Marcelo Messias Ferreira",
        alias: "João Marcelo",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/26.png?lm=1520611569",
        club: "EC Cruzeiro Belo Horizonte",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/744024-1697289524.jpg?lm=1",
      },
      {
        id: "393581",
        playerName: "Bruno Almeida",
        firstName: "Bruno",
        lastName: "Almeida",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/136.png?lm=1520611569",
        club: "CD Santa Clara",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/393581-1716925058.jpeg?lm=1",
      },
      {
        id: "545400",
        playerName: "Billal Messaoudi",
        firstName: "Billal",
        lastName: "Messaoudi",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/4.png?lm=1520611569",
        club: "Göztepe",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/545400-1700837753.png?lm=1",
      },
      {
        id: "401539",
        playerName: "Messias",
        firstName: "Messias",
        lastName: "Rodrigues da Silva Júnior",
        alias: "Messias",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/26.png?lm=1520611569",
        club: "Goiás EC",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/401539-1706143074.jpg?lm=1",
      },
      {
        id: "303939",
        playerName: "Ahmed El Messaoudi",
        firstName: "Ahmed",
        lastName: "El Messaoudi",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/107.png?lm=1520611569",
        club: "Tobol Kostanay",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/303939-1709555970.png?lm=1",
      },
      {
        id: "501087",
        playerName: "Soufiane Messeguem",
        firstName: "Soufiane",
        lastName: "Messeguem",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
        club: "Académico Viseu FC",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/501087-1611693573.jpg?lm=1",
      },
      {
        id: "417634",
        playerName: "Alexis Messidoro",
        firstName: "Alexis",
        lastName: "Messidoro",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/9.png?lm=1520611569",
        club: "PERSIS Solo",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/417634-1689734958.jpg?lm=1",
      },
      {
        id: "934154",
        playerName: "Amine Messoussa",
        firstName: "Amine",
        lastName: "Messoussa",
        alias: "",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/50.png?lm=1520611569",
        club: "FC Villefranche-Beaujolais",
        playerImage:
          "https://img.a.transfermarkt.technology/portrait/medium/934154-1711305526.jpg?lm=1",
      },
    ],
    coaches: [
      {
        id: "8954",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Nourreddine Messelmani",
        firstName: "Nourreddine",
        lastName: "Messelmani",
        alias: "",
        currentFunction: "Physiotherapeut",
        club: "Vereinslos",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
      },
      {
        id: "12726",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Hans Messing",
        firstName: "Hans",
        lastName: "Messing",
        alias: "",
        currentFunction: "Betreuer",
        club: "Vereinslos",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
      },
      {
        id: "19704",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Luc-Arsène Diamesso",
        firstName: "Luc-Arsène",
        lastName: "Diamesso",
        alias: "",
        currentFunction: "Trainer",
        club: "SV Molbergen",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/85.png?lm=1520611569",
      },
      {
        id: "22598",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Kurt Messner",
        firstName: "Kurt",
        lastName: "Messner",
        alias: "",
        currentFunction: "Trainer",
        club: "---",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/127.png?lm=1520611569",
      },
      {
        id: "29420",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/29420-1693178668.png?lm=1",
        coachName: "Gernot Messner",
        firstName: "Gernot",
        lastName: "Messner",
        alias: "",
        currentFunction: "Trainer",
        club: "Grazer AK 1902",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/127.png?lm=1520611569",
      },
      {
        id: "31667",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Ovidio Messa",
        firstName: "Ovidio",
        lastName: "Messa",
        alias: "",
        currentFunction: "Trainer",
        club: "---",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/23.png?lm=1520611569",
      },
      {
        id: "32005",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Nico Messina",
        firstName: "Nico",
        lastName: "Messina",
        alias: "",
        currentFunction: "Co-Trainer",
        club: "SV Reislingen/Neuhaus",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/75.png?lm=1520611569",
      },
      {
        id: "33751",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Volker Messner",
        firstName: "Volker",
        lastName: "Messner",
        alias: "",
        currentFunction: "Trainer",
        club: "Vereinslos",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
      },
      {
        id: "36982",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        coachName: "Marcelo Messina",
        firstName: "Marcelo",
        lastName: "Messina",
        alias: "",
        currentFunction: "Trainer",
        club: "CD Alfonso Ugarte de Puno",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/9.png?lm=1520611569",
      },
      {
        id: "37818",
        coachImage:
          "https://img.a.transfermarkt.technology/portrait/medium/37818-1503248217.jpg?lm=1",
        coachName: "Patrick Messow",
        firstName: "Patrick",
        lastName: "Messow",
        alias: "",
        currentFunction: "Sportdirektor",
        club: "Atlético Baleares",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
      },
    ],
    clubs: [
      {
        id: "6303",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/6303.png?lm=1638391347",
      },
      {
        id: "16418",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko U23",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/16418.png?lm=1638391347",
      },
      {
        id: "26092",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko U20",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/26092.png?lm=1638391347",
      },
      {
        id: "1104",
        league: "IT3C",
        competitionID: "IT3C",
        competitionName: "Serie C - C",
        name: "ACR Messina",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/1104.png?lm=1569236748",
      },
      {
        id: "47231",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko U16",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/47231.png?lm=1638391348",
      },
      {
        id: "51023",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko U18",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/51023.png?lm=1638391347",
      },
      {
        id: "23134",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko U17",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/23134.png?lm=1638391347",
      },
      {
        id: "48724",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko U15",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/48724.png?lm=1638391348",
      },
      {
        id: "92717",
        league: "FS",
        competitionID: "FS",
        competitionName: "Freundschaftsspiele",
        name: "Mexiko U19",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/default.png?lm=1457423031",
      },
      {
        id: "84940",
        league: "",
        competitionID: "",
        competitionName: "",
        name: "FC Guipry-Messac",
        logoImage:
          "https://tmssl.akamaized.net/images/wappen/medium/84940.png?lm=1616780488",
      },
    ],
    referees: [
      {
        id: "218",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Stefan Meßner",
        firstName: "Stefan",
        lastName: "Meßner",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/127.png?lm=1520611569",
      },
      {
        id: "305",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/305-1404475204.jpg?lm=1",
        refereeName: "Domenico Messina",
        firstName: "Domenico",
        lastName: "Messina",
        alias: "",
        club: "Karriereende",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/75.png?lm=1520611569",
      },
      {
        id: "316",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Matthew Messias",
        firstName: "Matthew",
        lastName: "Messias",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/189.png?lm=1520611569",
      },
      {
        id: "2908",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Jürgen Messmer",
        firstName: "Jürgen",
        lastName: "Messmer",
        alias: "",
        club: "Karriereende",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
      },
      {
        id: "2993",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Michael Messenbäck",
        firstName: "Michael",
        lastName: "Messenbäck",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/127.png?lm=1520611569",
      },
      {
        id: "3726",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Riadh Messai",
        firstName: "Riadh",
        lastName: "Messai",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/173.png?lm=1520611569",
      },
      {
        id: "4865",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Günter Messner",
        firstName: "Günter",
        lastName: "Messner",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/127.png?lm=1520611569",
      },
      {
        id: "6563",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Messie Nkounkou",
        firstName: "Messie",
        lastName: "Nkounkou",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/85.png?lm=1520611569",
      },
      {
        id: "7554",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Marc Messinger",
        firstName: "Marc",
        lastName: "Messinger",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
      },
      {
        id: "7788",
        refereeImage:
          "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
        refereeName: "Christian Messerli",
        firstName: "Christian",
        lastName: "Messerli",
        alias: "",
        club: "Unbekannt",
        nationImage:
          "https://tmssl.akamaized.net/images/flagge/verysmall/148.png?lm=1520611569",
      },
    ],
    competitions: [
      {
        id: "MSPO",
        competitionName: "Messestädte-Pokal (-1971)",
        competitionImage:
          "https://tmssl.akamaized.net/images/logo/medium/mspo.png?lm=1587466151",
        country: "",
        countryImage: "",
      },
    ],
  },
};
