export const dummyPlayersList = [
  {
    id: "324358",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 820278000,
    countryId: "189",
    clubId: "405",
    playerInfo: {
      id: "324358",
      name: "Ollie Watkins",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/324358-1708341279.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/324358-1708341279.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "363205",
    marketValue: { value: 65000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 860018400,
    countryId: "26",
    clubId: "11",
    playerInfo: {
      id: "363205",
      name: "Gabriel Jesus",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/363205-1669711141.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/363205-1669711141.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "318528",
    marketValue: { value: 65000000, currency: "€", progression: 1 },
    marketValueDate: 1717538400,
    birthday: 870818400,
    countryId: "50",
    clubId: "46",
    playerInfo: {
      id: "318528",
      name: "Marcus Thuram",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/318528-1662966601.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/318528-1662966601.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "444523",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 872632800,
    countryId: "26",
    clubId: "379",
    playerInfo: {
      id: "444523",
      name: "Lucas Paquetá",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/444523-1695370009.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/444523-1695370009.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "344381",
    marketValue: { value: 65000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 879462000,
    countryId: "50",
    clubId: "631",
    playerInfo: {
      id: "344381",
      name: "C. Nkunku",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/344381-1663686834.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/344381-1663686834.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "325443",
    marketValue: { value: 65000000, currency: "€", progression: 1 },
    marketValueDate: 1717624800,
    birthday: 896911200,
    countryId: "147",
    clubId: "336",
    playerInfo: {
      id: "325443",
      name: "V. Gyökeres",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/325443-1693591840.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/325443-1693591840.jpg?lm=1",
      imageSource: "Sporting CP",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "326031",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716933600,
    birthday: 934408800,
    countryId: "122",
    clubId: "27",
    playerInfo: {
      id: "326031",
      name: "M. de Ligt",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/326031-1700659567.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/326031-1700659567.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "357498",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 949014000,
    countryId: "215",
    clubId: "506",
    playerInfo: {
      id: "357498",
      name: "D. Vlahović",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/357498-1683293071.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/357498-1683293071.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "486049",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 1022450400,
    countryId: "19",
    clubId: "281",
    playerInfo: {
      id: "486049",
      name: "Jérémy Doku",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/486049-1666699113.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/486049-1666699113.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "610442",
    marketValue: { value: 65000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 1044313200,
    countryId: "39",
    clubId: "985",
    playerInfo: {
      id: "610442",
      name: "Rasmus Højlund",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/610442-1699471458.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/610442-1699471458.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "203460",
    marketValue: { value: 60000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 810684000,
    countryId: "189",
    clubId: "281",
    playerInfo: {
      id: "203460",
      name: "Jack Grealish",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/203460-1676499047.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/203460-1676499047.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "516716",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 858639600,
    countryId: "26",
    clubId: "506",
    playerInfo: {
      id: "516716",
      name: "Bremer",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/516716-1661269026.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/516716-1661269026.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "288230",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717365600,
    birthday: 863647200,
    countryId: "50",
    clubId: "583",
    playerInfo: {
      id: "288230",
      name: "O. Dembélé",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/288230-1684148641.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/288230-1684148641.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "339808",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 876088800,
    countryId: "50",
    clubId: "5",
    playerInfo: {
      id: "339808",
      name: "Theo Hernández",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/339808-1663574533.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/339808-1663574533.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Lateral izquierdo",
          shortName: "LI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "258923",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 878252400,
    countryId: "189",
    clubId: "985",
    playerInfo: {
      id: "258923",
      name: "Marcus Rashford",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/258923-1674473054.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/258923-1674473054.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "401530",
    marketValue: { value: 60000000, currency: "€", progression: -1 },
    marketValueDate: 1717711200,
    birthday: 885078000,
    countryId: "26",
    clubId: "418",
    playerInfo: {
      id: "401530",
      name: "Éder Militão",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/401530-1689002515.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/401530-1689002515.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "355915",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 893628000,
    countryId: "9",
    clubId: "148",
    playerInfo: {
      id: "355915",
      name: "Cristian Romero",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/355915-1665609429.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/355915-1665609429.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "398073",
    marketValue: { value: 60000000, currency: "€", progression: -1 },
    marketValueDate: 1717365600,
    birthday: 910134000,
    countryId: "107",
    clubId: "583",
    playerInfo: {
      id: "398073",
      name: "Achraf Hakimi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/398073-1672304327.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/398073-1672304327.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Lateral derecho",
          shortName: "LD",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "368887",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1716933600,
    birthday: 950655600,
    countryId: "19",
    clubId: "23826",
    playerInfo: {
      id: "368887",
      name: "Loïs Openda",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/368887-1713944805.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/368887-1713944805.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "503733",
    marketValue: { value: 60000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 982969200,
    countryId: "189",
    clubId: "762",
    playerInfo: {
      id: "503733",
      name: "Anthony Gordon",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/503733-1660588736.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/503733-1660588736.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "709187",
    marketValue: { value: 60000000, currency: "€", progression: 1 },
    marketValueDate: 1717711200,
    birthday: 1026424800,
    countryId: "157",
    clubId: "621",
    playerInfo: {
      id: "709187",
      name: "Nico Williams",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/709187-1709676169.png?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/709187-1709676169.png?lm=1",
      imageSource: "Athletic Club",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "810092",
    marketValue: { value: 60000000, currency: "€", progression: 0 },
    marketValueDate: 1717365600,
    birthday: 1141772400,
    countryId: "50",
    clubId: "583",
    playerInfo: {
      id: "810092",
      name: "W. Zaïre-Emery",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/810092-1672303575.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/810092-1672303575.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "7", name: "Mediocentro", shortName: "MC", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "148455",
    marketValue: { value: 55000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 708559200,
    countryId: "2",
    clubId: "31",
    playerInfo: {
      id: "148455",
      name: "Mohamed Salah",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/148455-1700651360.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/148455-1700651360.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "257455",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 805240800,
    countryId: "136",
    clubId: "931",
    playerInfo: {
      id: "257455",
      name: "João Palhinha",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/257455-1684773447.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/257455-1684773447.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "6", name: "Pivote", shortName: "PIV", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "335721",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 876261600,
    countryId: "189",
    clubId: "11",
    playerInfo: {
      id: "335721",
      name: "Ben White",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/335721-1683275943.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/335721-1683275943.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Lateral derecho",
          shortName: "LD",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "479999",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 899071200,
    countryId: "189",
    clubId: "873",
    playerInfo: {
      id: "479999",
      name: "Eberechi Eze",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/479999-1678466922.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/479999-1678466922.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "395516",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 931298400,
    countryId: "50",
    clubId: "405",
    playerInfo: {
      id: "395516",
      name: "Moussa Diaby",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/395516-1642608355.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/395516-1642608355.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "487465",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 952556400,
    countryId: "136",
    clubId: "543",
    playerInfo: {
      id: "487465",
      name: "Pedro Neto",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/487465-1709158892.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/487465-1709158892.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "431755",
    marketValue: { value: 55000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 956613600,
    countryId: "147",
    clubId: "148",
    playerInfo: {
      id: "431755",
      name: "D. Kulusevski",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/431755-1684943454.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/431755-1684943454.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "557459",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 987631200,
    countryId: "122",
    clubId: "148",
    playerInfo: {
      id: "557459",
      name: "M. van de Ven",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/557459-1657202743.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/557459-1657202743.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "566723",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1716760800,
    birthday: 1008111600,
    countryId: "50",
    clubId: "873",
    playerInfo: {
      id: "566723",
      name: "Michael Olise",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/566723-1696598775.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/566723-1696598775.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "616341",
    marketValue: { value: 55000000, currency: "€", progression: -1 },
    marketValueDate: 1717365600,
    birthday: 1024437600,
    countryId: "136",
    clubId: "583",
    playerInfo: {
      id: "616341",
      name: "Nuno Mendes",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/616341-1672304855.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/616341-1672304855.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Lateral izquierdo",
          shortName: "LI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "670681",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1717624800,
    birthday: 1096236000,
    countryId: "136",
    clubId: "294",
    playerInfo: {
      id: "670681",
      name: "João Neves",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/670681-1701295511.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/670681-1701295511.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "6", name: "Pivote", shortName: "PIV", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "971570",
    marketValue: { value: 55000000, currency: "€", progression: 1 },
    marketValueDate: 1711580400,
    birthday: 1153432800,
    countryId: "26",
    clubId: "1023",
    playerInfo: {
      id: "971570",
      name: "Endrick",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/971570-1682691107.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/971570-1682691107.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "88755",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1716760800,
    birthday: 678060000,
    countryId: "19",
    clubId: "281",
    playerInfo: {
      id: "88755",
      name: "Kevin De Bruyne",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/88755-1713391485.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/88755-1713391485.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "181767",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1717365600,
    birthday: 768866400,
    countryId: "26",
    clubId: "583",
    playerInfo: {
      id: "181767",
      name: "Marquinhos",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/181767-1672303747.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/181767-1672303747.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "161056",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1716933600,
    birthday: 792198000,
    countryId: "40",
    clubId: "27",
    playerInfo: {
      id: "161056",
      name: "Joshua Kimmich",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/161056-1700039639.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/161056-1700039639.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Lateral derecho",
          shortName: "LD",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "251664",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 826930800,
    countryId: "189",
    clubId: "1148",
    playerInfo: {
      id: "251664",
      name: "Ivan Toney",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/251664-1677676808.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/251664-1677676808.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Delantero centro",
          shortName: "DEL",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "353366",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 827967600,
    countryId: "50",
    clubId: "46",
    playerInfo: {
      id: "353366",
      name: "Benjamin Pavard",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/353366-1713819215.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/353366-1713819215.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Defensa central",
          shortName: "CEN",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "243714",
    marketValue: { value: 50000000, currency: "€", progression: -1 },
    marketValueDate: 1716933600,
    birthday: 834616800,
    countryId: "50",
    clubId: "27",
    playerInfo: {
      id: "243714",
      name: "Kingsley Coman",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/243714-1700040256.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/243714-1700040256.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "338424",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717711200,
    birthday: 835394400,
    countryId: "157",
    clubId: "681",
    playerInfo: {
      id: "338424",
      name: "Mikel Merino",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/338424-1716803831.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/338424-1716803831.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "7", name: "Mediocentro", shortName: "MC", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "340950",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 849654000,
    countryId: "136",
    clubId: "31",
    playerInfo: {
      id: "340950",
      name: "Diogo Jota",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/340950-1716296423.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/340950-1716296423.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "411295",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717711200,
    birthday: 850518000,
    countryId: "26",
    clubId: "131",
    playerInfo: {
      id: "411295",
      name: "Raphinha",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/411295-1665127690.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/411295-1665127690.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "314875",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 851036400,
    countryId: "189",
    clubId: "379",
    playerInfo: {
      id: "314875",
      name: "Jarrod Bowen",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/314875-1662362005.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/314875-1662362005.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Extremo derecho",
          shortName: "ED",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "198116",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717538400,
    birthday: 879116400,
    countryId: "75",
    clubId: "46",
    playerInfo: {
      id: "198116",
      name: "F. Dimarco",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/198116-1661511006.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/198116-1661511006.jpg?lm=1",
      imageSource: "imago images",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Lateral izquierdo",
          shortName: "LI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "360518",
    marketValue: { value: 50000000, currency: "€", progression: 1 },
    marketValueDate: 1717538400,
    birthday: 888620400,
    countryId: "122",
    clubId: "800",
    playerInfo: {
      id: "360518",
      name: "T. Koopmeiners",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/360518-1707302998.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/360518-1707302998.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "293385",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716933600,
    birthday: 894492000,
    countryId: "157",
    clubId: "23826",
    playerInfo: {
      id: "293385",
      name: "Dani Olmo",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/293385-1711546268.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/293385-1711546268.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Mediocentro ofensivo",
          shortName: "MCO",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "601883",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 904168800,
    countryId: "136",
    clubId: "281",
    playerInfo: {
      id: "601883",
      name: "Matheus Nunes",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/601883-1693561106.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/601883-1693561106.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "7", name: "Mediocentro", shortName: "MC", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "423440",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1717711200,
    birthday: 917910000,
    countryId: "157",
    clubId: "681",
    playerInfo: {
      id: "423440",
      name: "M. Zubimendi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/423440-1684149419.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/423440-1684149419.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: { id: "6", name: "Pivote", shortName: "PIV", group: null },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
  {
    id: "434675",
    marketValue: { value: 50000000, currency: "€", progression: 0 },
    marketValueDate: 1716760800,
    birthday: 926028000,
    countryId: "122",
    clubId: "31",
    playerInfo: {
      id: "434675",
      name: "Cody Gakpo",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/434675-1682690965.jpg?lm=1",
      imageLarge:
        "https://img.a.transfermarkt.technology/portrait/big/434675-1682690965.jpg?lm=1",
      imageSource: "IMAGO",
      shirtNumber: null,
      age: null,
      dateOfBirth: null,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Extremo izquierdo",
          shortName: "EI",
          group: null,
        },
        second: null,
        third: null,
      },
      nationalities: null,
      marketValue: null,
    },
  },
];
